#include "texture_converter.h"

#include <godot_cpp/classes/image.hpp>
#include <godot_cpp/variant/packed_byte_array.hpp>
#include <godot_cpp/variant/utility_functions.hpp>

#include <cstring>

namespace quebratsk::converters {

using namespace godot;

Ref<ImageTexture> TextureConverter::convert(const ir::IRTextureData& ir_tex) {
    if (!ir_tex.is_valid()) {
        UtilityFunctions::printerr("[TextureConverter] Malformed texture data for '",
                                   String(ir_tex.name.c_str()), "'.");
        return {};
    }

    PackedByteArray data;
    data.resize(static_cast<int64_t>(ir_tex.rgba8_pixels.size()));
    std::memcpy(data.ptrw(), ir_tex.rgba8_pixels.data(), ir_tex.rgba8_pixels.size());

    Ref<Image> image = Image::create_from_data(
        static_cast<int32_t>(ir_tex.width),
        static_cast<int32_t>(ir_tex.height),
        false,                 // mipmaps are generated by the importer if requested
        Image::FORMAT_RGBA8,
        data);

    if (image.is_null()) {
        UtilityFunctions::printerr("[TextureConverter] Image::create_from_data failed for '",
                                   String(ir_tex.name.c_str()), "'.");
        return {};
    }

    return ImageTexture::create_from_image(image);
}

} // namespace quebratsk::converters
