@tool
extends RefCounted

## What a map's entities mean, rather than what they literally say.
##
## A `.bsp` gives you `{"classname": "ambient_generic", "health": "8", "spawnflags": "17"}` and
## nothing else. That health is a volume out of ten, and bit 16 of those flags means the sound
## waits for a trigger, are facts about the game that the map file never carries.
##
## `data/goldsrc_entities.json` carries them, generated by `tools/build_entity_catalogue.py`
## from the FGD files the level editors used. 520 classes across seven games.

const PATH := "res://addons/quebratsk_editor/data/goldsrc_entities.json"

static var _entities: Dictionary = {}
static var _loaded := false


## Everything the schema says about one class of entity.
static func describe(classname: String) -> Dictionary:
	_load()
	return _entities.get(classname.to_lower(), {})


## What this entity is, in words a person can read, or the classname when nothing is known.
##
## "Universal sound Ambient" rather than "ambient_generic", which is the difference between a
## list somebody can scan and a list of identifiers.
static func label(classname: String) -> String:
	var described := describe(classname)
	var text := str(described.get("description", ""))
	return classname if text.is_empty() else text


## Is this entity a shape carved out of the level, or a point in space?
static func is_brush(classname: String) -> bool:
	return str(describe(classname).get("kind", "point")) == "brush"


## The names of every spawnflag bit set on this entity.
##
## Turns 17 into ["Play Everywhere", "Start Silent"], which is what the mapper actually chose.
static func flags_set(classname: String, spawnflags: int) -> PackedStringArray:
	var out := PackedStringArray()
	for f in describe(classname).get("spawnflags", []):
		var bit := int((f as Dictionary).get("bit", 0))
		if bit != 0 and (spawnflags & bit) != 0:
			out.append(str((f as Dictionary).get("means", "")))
	return out


## Whether a named spawnflag is set, matched loosely on its description.
##
## Matching on the word rather than on the number is deliberate. A bit means different things
## in different entities, and code that says `flag_set(cls, flags, "start silent")` states its
## intent where `flags & 16` states an implementation detail that was true when it was written.
static func flag_set(classname: String, spawnflags: int, means: String) -> bool:
	var wanted := means.to_lower()
	for f in describe(classname).get("spawnflags", []):
		var bit := int((f as Dictionary).get("bit", 0))
		if bit == 0 or (spawnflags & bit) == 0:
			continue
		if str((f as Dictionary).get("means", "")).to_lower().contains(wanted):
			return true
	return false


## What a key on this entity is for, as the schema describes it.
##
## `key_label("ambient_generic", "health")` is "Volume (10 = loudest)", which is the sort of
## thing that otherwise has to be worked out by reading engine source.
static func key_label(classname: String, key: String) -> String:
	var keys: Dictionary = describe(classname).get("keys", {})
	var entry: Dictionary = keys.get(key.to_lower(), {})
	return str(entry.get("label", ""))


## Group a map's entities by what they are, for anything that has to summarise a level.
##
## Returns { "Invisible lightsource": 12, "Basic door": 8 } rather than a tally of classnames,
## so a level can be described instead of enumerated.
static func summarise(entities: Array) -> Dictionary:
	var counts := {}
	for e in entities:
		var cls := str((e as Dictionary).get("classname", ""))
		if cls.is_empty():
			continue
		var name := label(cls)
		counts[name] = int(counts.get(name, 0)) + 1
	return counts


static func _load() -> void:
	if _loaded:
		return
	_loaded = true

	var file := FileAccess.open(PATH, FileAccess.READ)
	if file == null:
		push_warning("Entity catalogue missing at %s; entities stay unexplained." % PATH)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if parsed is Dictionary and (parsed as Dictionary).has("entities"):
		_entities = (parsed as Dictionary)["entities"]
	else:
		push_warning("Entity catalogue at %s is not readable." % PATH)
