@tool
extends RefCounted

## The noise a Counter-Strike level makes that no model records.
##
## A `.mdl` names the sounds its own animations trigger, which covers a gunshot and very little
## else. Everything else a player does comes out of the game library: footsteps that depend on
## what you are standing on, the C4 beeping and being planted and going off, a grenade bouncing
## off a wall, hitting flesh, taking a fall, drowning, the radio, the hostages.
##
## None of that is in a file Quebratsk reads, which is why an imported character stood in
## perfect silence and why the only sound in the sandbox was a gunshot.
##
## `data/cs_sounds.json` carries the names, generated by `tools/build_sound_catalogue.py` from
## ReGameDLL_CS. A name there is a claim about the game's code and not a promise that the file
## is installed; `demo/tests/verify_sounds_resolve.gd` is what answers that.

const PATH := "res://addons/quebratsk_editor/data/cs_sounds.json"

## What a surface makes underfoot, by the letter GoldSrc puts at the front of a texture name.
##
## The engine does not store a material per face. It reads the first character of the texture's
## name — `CHAR_TEX_METAL` is 'M', vents are 'V', dirt 'D' — which is why a mapper renames a
## texture to change how the floor sounds. From `PM_MapTextureTypeStepType` and
## `CBasePlayer::UpdateStepSound`.
const BY_TEXTURE_LETTER := {
	"m": "metal", "v": "duct", "d": "dirt", "s": "slosh", "t": "tile",
	"g": "grate", "w": "wood", "p": "computer", "y": "glass", "n": "snow",
}

static var _groups: Dictionary = {}
static var _loaded := false


## Every sound name in a group, e.g. "c4_beep" or "footstep".
static func group(label: String) -> PackedStringArray:
	_load()
	var entry: Dictionary = _groups.get(label, {})
	var out := PackedStringArray()
	for file in entry.get("files", []):
		out.append(str(file))
	return out


## The names of every group there is, for anything that wants to enumerate them.
static func groups() -> PackedStringArray:
	_load()
	return PackedStringArray(_groups.keys())


## The footsteps for one kind of surface: "metal", "dirt", "tile" and so on.
##
## Falls back to the default concrete step, which is what the engine does for a texture whose
## first letter means nothing to it.
static func footsteps(surface := "") -> PackedStringArray:
	var all := group("footstep")
	if surface.is_empty():
		surface = "step"
	var wanted := PackedStringArray()
	for name in all:
		if str(name).contains("pl_%s" % surface):
			wanted.append(str(name))
	if wanted.is_empty() and surface != "step":
		return footsteps("step")
	return wanted


## Which surface a texture name implies, by the letter GoldSrc reads off the front of it.
static func surface_of_texture(texture: String) -> String:
	if texture.is_empty():
		return ""
	return str(BY_TEXTURE_LETTER.get(texture[0].to_lower(), ""))


## One name from a group, at random, as the game does.
static func any_of(label: String, rng: RandomNumberGenerator = null) -> String:
	var names := group(label)
	if names.is_empty():
		return ""
	if rng == null:
		return str(names[randi() % names.size()])
	return str(names[rng.randi_range(0, names.size() - 1)])


static func _load() -> void:
	if _loaded:
		return
	_loaded = true

	var file := FileAccess.open(PATH, FileAccess.READ)
	if file == null:
		push_warning("Sound catalogue missing at %s; nothing but gunshots will be heard." % PATH)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if parsed is Dictionary and (parsed as Dictionary).has("groups"):
		_groups = (parsed as Dictionary)["groups"]
	else:
		push_warning("Sound catalogue at %s is not readable." % PATH)
